version: "3.9"

services:
  api:
    image: node:21-alpine3.18
    container_name: api
    restart: always
    tty: true
    working_dir: /api
    volumes:
      - ./api:/api
      - ./docker/entrypoint.sh:/entrypoint.sh
    networks:
      - api-network
      - infra-network
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5
    depends_on:
      - database
    entrypoint: "/entrypoint.sh"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5
    networks:
      - api-network
    depends_on:
      - api

  database:
    image: mariadb:11.3.1-rc-jammy
    container_name: database
    restart: always
    tty: true
    networks:
      - infra-network
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5
    volumes:
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=8ujeG647
      - MYSQL_DATABASE=api
      - MYSQL_PASSWORD=password

networks:
  api-network:
  infra-network:
